services:
  database:
    image: mongo
    container_name: mongodb
    attach: false
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    networks:
      - stock-manager-network

networks:
  stock-manager-network:
    driver: bridge
