services:
  api:
    build: .
    container_name: node-api
    ports:
      - 3030:3030
    volumes:
      - .:/app
      - /node_modules
    networks:
      stock-manager-network:
        ipv4_address: 172.34.0.2

  database:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    networks:
      stock-manager-network:
        ipv4_address: 172.34.0.3

    
networks:
  stock-manager-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.34.0.0/16